FROM hashicorp/vault:latest

COPY put-secrets.sh /usr/local/bin/
COPY healthcheck.sh /usr/local/bin/
COPY env-vault.json /usr/local/bin/

RUN chmod +x /usr/local/bin/put-secrets.sh 
RUN chmod +x /usr/local/bin/healthcheck.sh

CMD vault server -dev & sleep 5 && /usr/local/bin/put-secrets.sh && tail -f /dev/null
