global:
    scrape_interval: 15s # By default, scrape targets every 15 seconds.
    evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']

    - job_name: 'api-gateway'
      basic_auth:
          username: admin
          password: admin
      static_configs:
          - targets: ['api-gateway:3000']
      metrics_path: /api/metrics

    - job_name: 'cadvisor'
      static_configs:
          - targets: ['cadvisor:8080']
